### ISSUE TITLE
Consider using streaming HTTP connection instead of Websockets for watches

### ISSUE THREAD

**Issue by ilackarms** [openshift/prometheus-alert-buffer#1]
What are the advantages of using Websockets over simple HTTP / TCP streaming?

I ask because websocket protocol is a bit complicated; a client won't be able to start a watch with a basic HTTP GET. They'll have to use a websocket client library, most likely (unless they know the websocket protocol and can negotiate the upgrade over basic http).

I think websockets are better suited for bidirectional message passing; however our API does not support client-to-server messages. Since messages are only passed one way, server-to-client, I think streaming HTTP body might be better for our use case. For example, with resource watches, Kubernetes uses HTTP streaming body.

Thoughts on this?

**Comment by juliusv** [comment]
@ilackarms I think that makes sense. I was also thinking of Kubernetes before I finished reading your text.

**Comment by ilackarms** [comment]
![](http://i2.kym-cdn.com/photos/images/masonry/000/037/491/f5.gif)

**Comment by moolitayer** [comment]
:+1: for this direction.
I have been fighting with http/websocket upgrade prior to learning one of the proxies we have along the way (origin/oauth-proxy) does not support connection upgrade. Chunked HTTP will also remove the need to deal with connection upgrade in the alert collection code.

**Comment by DirectXMan12** [comment]
> For example, with resource watches, Kubernetes uses HTTP streaming body.

Kubernetes supports both, I believe.  The origin web console uses the websockets for watches, for instance (probably because consuming chunked HTTP from the browser, IIRC, is a bit clunky).
